
from ColasConPrioridad import Priorityqueue

cp = Priorityqueue()
cp.enqueue((1,'Sofia'))
cp.enqueue((5,'Axel'))
cp.enqueue((1,'Camila'))
cp.enqueue((2,'Ariok'))
cp.enqueue((3,'Brad'))
cp.enqueue((4,'Victor'))
cp.enqueue((1,'Andrea'))
cp.to_string()
print(cp.length())
cp.dequeue()
cp.to_string()
print(cp.length())
cp.dequeue()
cp.to_string()
print(cp.length())
cp.dequeue()
cp.to_string()
print(cp.length())
cp.dequeue()
cp.to_string()
print(cp.length())
cp.dequeue()
cp.to_string()
print(cp.length())
cp.dequeue()
cp.to_string()
print(cp.length())
cp.dequeue()
cp.to_string()
print(cp.length())
cp.dequeue()
